### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by shikhasingh1797** [youngmki/py-dreambooth#1]
(myenv1) PS D:\py-dreambooth> python .\zz.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.8.10 (you have 3.8.18)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File ".\zz.py", line 2, in <module>
    from py_dreambooth.model import SdDreamboothModel
  File "C:\Users\N_B\Miniconda3\envs\myenv1\lib\site-packages\py_dreambooth\model.py", line 49, in <module>
    class SchedulerConfig(Dict, Enum):
  File "C:\Users\N_B\Miniconda3\envs\myenv1\lib\enum.py", line 150, in __prepare__
    member_type, first_enum = metacls._get_mixins_(cls, bases)
  File "C:\Users\N_B\Miniconda3\envs\myenv1\lib\enum.py", line 574, in _get_mixins_
    member_type = _find_data_type(bases) or object
  File "C:\Users\N_B\Miniconda3\envs\myenv1\lib\enum.py", line 562, in _find_data_type
    raise TypeError('%r: too many data types: %r' % (class_name, data_types))
TypeError: 'SchedulerConfig': too many data types: [<class 'dict'>, <class 'typing.Generic'>]

**Comment by youngmki** [comment]
My guess is that Mixin for Dict in Enum is not supported in Python 3.8.  Since this isn't a very important part of my code, I've redistributed it, removing all the parts that might be problematic. Please try installing the latest version and let me know if you run into the same problem.
